// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9popznvxbH7NjQwrEItJqDHHzpA3QPXQ',
    appId: '1:1015107851143:web:fbd97cfb4a9781693ff922',
    messagingSenderId: '1015107851143',
    projectId: 'moviesapp-83f29',
    authDomain: 'moviesapp-83f29.firebaseapp.com',
    storageBucket: 'moviesapp-83f29.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6toXAhiInmMW5jLELnapgG-PE2IjPfJE',
    appId: '1:1015107851143:android:cf7fe979fc4992063ff922',
    messagingSenderId: '1015107851143',
    projectId: 'moviesapp-83f29',
    storageBucket: 'moviesapp-83f29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3JB_OQ8NPNDm0taMIwbO2gv6nqi2r27U',
    appId: '1:1015107851143:ios:5fb8d40b5e5fc7c83ff922',
    messagingSenderId: '1015107851143',
    projectId: 'moviesapp-83f29',
    storageBucket: 'moviesapp-83f29.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );
}
